version: "3.9"

services:
  api:
    build:
      dockerfile: ./docker/api/Dockerfile
    container_name: gitlab-board-api
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - "48001:8000"
    env_file: .env

  postgres:
    image: postgres:14-alpine3.16
    container_name: gitlab-board-postgres
    restart: unless-stopped
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d board -U board" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: board
      POSTGRES_USER: board
      POSTGRES_PASSWORD: board

  frontend:
    build:
      dockerfile: ./docker/frontend/Dockerfile
    container_name: gitlab-board-frontend
    restart: unless-stopped
    command: "sh -c 'npm run prod'"
    ports:
      - "48002:8000"
    env_file: .env

volumes:
  pg-data:
